# Dependencies
# markdown:         redcarpet
# the following configures "github-flavored markdown" 
markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     "with_toc_data"]
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            wm65
tagline:          'online now'
description:      'Infos for wm and friends.'
url:              http://wm65.github.io

author:
  name:           'Werner Mueller'
  url:            https://wm65.github.io

paginate:         1

pages_list:       
  About: '/about'
  Categories: '/categories/index.html'
  Archive: '/archive'
  Feed: '/atom.xml'


# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/wm65/wm65.github.io
