# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            wm65
tagline:          'The Jekyll Butler'
description:      'Base theme for Jekyll themes by @mdo.'
url:              http://wm65.github.io

author:
  name:           'Werner Mueller'
  url:            https://wm65.github.io

paginate:         1

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'


# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/wm65/wm65.github.io
